---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubectl-configmap
  namespace: argocd
data:
  kubectl: |
    #!/bin/sh
    set -euo pipefail

    # Install kubectl
    curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl

    # Run kubectl command
    ./kubectl "$@"
---
{{- range $filepath, $_ := .Files.Glob "dockerfile_inputs/**" -}}
{{- if (hasSuffix "Dockerfile" $filepath) }}
{{- $dockersha256 := (sha256sum ($.Files.Get $filepath)) }}
{{- $basename := ($filepath | regexFind "[a-zA-Z0-9.-]*:[a-zA-Z0-9.-]*" | replace ":" "-" ) }}
{{- $sha_suffix := substr 0 10 $dockersha256 }}
{{- $basename_sha_suffix := printf "%s-%s" $basename $sha_suffix }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ $basename_sha_suffix }}
  namespace: argocd
data:
  dockerfile: |
  {{- $.Files.Get $filepath | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-{{ $basename_sha_suffix }}
  namespace: argocd
  labels:
    app: kaniko-job
spec:
# ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      # next two lines bind service account to Pod
      serviceAccountName: kaniko-get-list-pod-serviceaccount
      automountServiceAccountToken: true
      containers:
      - name:  pod-job-{{ $basename_sha_suffix }}
        image: gcr.io/kaniko-project/executor:debug
        args: [
                 "--context=dir://workspace",
                 {{- $versionlookuppath := ($filepath | replace ":" "-" ) }}
                 {{- $version := get $.Values.versionLookup $versionlookuppath -}}
                 {{- $destination := printf "\"--destination=gcorradini2023/%s:%s\"" $basename $version -}}
                 {{ $destination | nindent 15 }},
                 "--dockerfile=Dockerfile"
        ]
        lifecycle:
          postStart:
            exec:
              #command: [ "/bin/sh", "-c", "if [ $(kubectl get pods -o jsonpath='{.status.containerStatuses[0].state.terminated.reason}' my-deployment) = Completed ]; then exit 0; else exit 1; fi" ]
              command: [ "/bin/sh", "-c", "if [ $(kubectl get pods -o jsonpath='{.status.containerStatuses[0].state.terminated.reason}' my-deployment) = Completed ]; then exit 0; else exit 1; fi" ]
          volumeMounts:
          - name: dockerhub-regcred-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-volume
            mountPath: /workspace
          - name: kubectl-configmap
            mountPath: /usr/local/bin/kubectl
      volumes:
        - name: dockerhub-regcred-secret
          secret:
            secretName: dockerhub-regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-volume
          configMap:
            name: configmap-{{ $basename_sha_suffix }}
            items:
              - key: dockerfile
                path: Dockerfile
        - name: kubectl-configmap
          configMap:
              name: kubectl-configmap
---
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-get-list-pod-serviceaccount
  namespace: argocd
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-pod-reader-role
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-pod-reader-role-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: kaniko-get-list-pod-serviceaccount
  namespace: argocd
roleRef:
  kind: Role
  name: kaniko-pod-reader-role
  apiGroup: rbac.authorization.k8s.io