---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-busybox-latest-51df75f61b
  namespace: argocd
data:
  dockerfile: |
    FROM busybox:latest
    # ARG VERSION=0.0.11
    ENTRYPOINT ["/busybox/sh", "-ec", "sleep 1000"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-python-buster-2f89b9ccd9
  namespace: argocd
data:
  dockerfile: |
    FROM python:buster
    # ARG VERSION=0.0.13
    ENTRYPOINT ["python", "-m", "http.server 8888"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ubuntu-lunar-9498811c6c
  namespace: argocd
data:
  dockerfile: |
    FROM ubuntu:lunar
    # ARG VERSION=0.0.15
    ENTRYPOINT ["/bin/bash", "-c", "echo Hello Kaniko from Kubernetes"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-busybox-latest-51df75f61b
  namespace: argocd
  labels:
    app: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  pod-job-busybox-latest-51df75f61b
        image: gcr.io/kaniko-project/executor:debug
        args: [
                 "--context=dir://workspace",
             "--destination=gcorradini2023/busybox-latest:0.0.11",
                 "--dockerfile=Dockerfile"
        ]
        volumeMounts:
          - name: dockerhub-regcred-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-volume
            mountPath: /workspace
      volumes:
        - name: dockerhub-regcred-secret
          secret:
            secretName: dockerhub-regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-volume
          configMap:
            name: configmap-busybox-latest-51df75f61b
            items:
              - key: dockerfile
                path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-python-buster-2f89b9ccd9
  namespace: argocd
  labels:
    app: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  pod-job-python-buster-2f89b9ccd9
        image: gcr.io/kaniko-project/executor:debug
        args: [
                 "--context=dir://workspace",
             "--destination=gcorradini2023/python-buster:0.0.13",
                 "--dockerfile=Dockerfile"
        ]
        volumeMounts:
          - name: dockerhub-regcred-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-volume
            mountPath: /workspace
      volumes:
        - name: dockerhub-regcred-secret
          secret:
            secretName: dockerhub-regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-volume
          configMap:
            name: configmap-python-buster-2f89b9ccd9
            items:
              - key: dockerfile
                path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-ubuntu-lunar-9498811c6c
  namespace: argocd
  labels:
    app: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  pod-job-ubuntu-lunar-9498811c6c
        image: gcr.io/kaniko-project/executor:debug
        args: [
                 "--context=dir://workspace",
             "--destination=gcorradini2023/ubuntu-lunar:0.0.15",
                 "--dockerfile=Dockerfile"
        ]
        volumeMounts:
          - name: dockerhub-regcred-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-volume
            mountPath: /workspace
      volumes:
        - name: dockerhub-regcred-secret
          secret:
            secretName: dockerhub-regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-volume
          configMap:
            name: configmap-ubuntu-lunar-9498811c6c
            items:
              - key: dockerfile
                path: Dockerfile
