---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-busybox-latest-6ad2b61d34
  namespace: argocd
data:
  dockerfile: |
    FROM busybox:latest
    ENV VERSION=0.0.11
    ENTRYPOINT ["/busybox/sh", "-ec", "sleep 5000"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-python-buster-ac80d1c7c5
  namespace: argocd
data:
  dockerfile: |
    FROM python:buster
    ENV VERSION=0.0.13
    ENTRYPOINT ["python", "-m", "http.server 9999"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ubuntu-lunar-a7c3a154a2
  namespace: argocd
data:
  dockerfile: |
    FROM ubuntu:lunar
    ENV VERSION=0.0.15
    
    # Set locale non-interactively
    ARG DEBIAN_FRONTEND=noninteractive
    ENV LANG C.UTF-8
    
    RUN apt-get -y update \
        && apt-get install -y --no-install-recommends \
                apt-utils \
                build-essential \
                curl \
                binutils \
                git \
                jq \
                locales \
                tzdata \
                wget \
        && apt-get clean -y \
        && rm -rf /var/lib/apt/lists/*
    
    # Set locale non-interactively
    RUN echo "America/Los_Angeles" > /etc/timezone \
        && dpkg-reconfigure -f noninteractive tzdata \
        && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
        && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
        && dpkg-reconfigure --frontend=noninteractive locales \
        && update-locale LANG=en_US.UTF-8
    
    
    #####################################
    # requirements install
    #####################################
    ENV APPLICATION_ROOT=/tmp \
        LANG=en_US.UTF-8 \
        LANGUAGE=en_US:en \
        LC_ALL=en_US.UTF-8 \
        TERM=linux \
        TERMINFO=/etc/terminfo
    
    WORKDIR $APPLICATION_ROOT
    ENTRYPOINT ["/bin/bash", "-c", "echo Hello Kaniko & Kubernetes"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-busybox-latest-6ad2b61d34
  namespace: argocd
  labels:
    app: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  pod-job-busybox-latest-6ad2b61d34
        image: gcr.io/kaniko-project/executor:debug
        args: [
                 "--context=dir://workspace",
               "--destination=gcorradini2023/busybox-latest:0.0.11",
                 "--dockerfile=Dockerfile"
        ]
        volumeMounts:
          - name: dockerhub-regcred-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-volume
            mountPath: /workspace
      volumes:
        - name: dockerhub-regcred-secret
          secret:
            secretName: dockerhub-regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-volume
          configMap:
            name: configmap-busybox-latest-6ad2b61d34
            items:
              - key: dockerfile
                path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-python-buster-ac80d1c7c5
  namespace: argocd
  labels:
    app: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  pod-job-python-buster-ac80d1c7c5
        image: gcr.io/kaniko-project/executor:debug
        args: [
                 "--context=dir://workspace",
               "--destination=gcorradini2023/python-buster:0.0.13",
                 "--dockerfile=Dockerfile"
        ]
        volumeMounts:
          - name: dockerhub-regcred-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-volume
            mountPath: /workspace
      volumes:
        - name: dockerhub-regcred-secret
          secret:
            secretName: dockerhub-regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-volume
          configMap:
            name: configmap-python-buster-ac80d1c7c5
            items:
              - key: dockerfile
                path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-ubuntu-lunar-a7c3a154a2
  namespace: argocd
  labels:
    app: kaniko-job
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  pod-job-ubuntu-lunar-a7c3a154a2
        image: gcr.io/kaniko-project/executor:debug
        args: [
                 "--context=dir://workspace",
               "--destination=gcorradini2023/ubuntu-lunar:0.0.15",
                 "--dockerfile=Dockerfile"
        ]
        volumeMounts:
          - name: dockerhub-regcred-secret
            mountPath: /kaniko/.docker
          - name: dockerfile-volume
            mountPath: /workspace
      volumes:
        - name: dockerhub-regcred-secret
          secret:
            secretName: dockerhub-regcred
            items:
              - key: .dockerconfigjson
                path: config.json
        - name: dockerfile-volume
          configMap:
            name: configmap-ubuntu-lunar-a7c3a154a2
            items:
              - key: dockerfile
                path: Dockerfile
