---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-busybox-latest-040b693780
  namespace: argocd
data:
  dockerfile: |
    FROM busybox:latest
    ENTRYPOINT ["/busybox/sh", "-ec", "sleep 4000"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-python-buster-4a16c7408b
  namespace: argocd
data:
  dockerfile: |
    FROM python:buster
    ENTRYPOINT ["python", "-m", "http.server 8888"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ubuntu-lunar-389375b53e
  namespace: argocd
data:
  dockerfile: |
    FROM ubuntu:lunar
    ENTRYPOINT ["/bin/bash", "-c", "echo Hello Kaniko from Kubernetes"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox-latest-040b693780
  namespace: argocd
spec:
  restartPolicy: Never
  containers:
  - name:  pod-busybox-latest-040b693780
    image: gcr.io/kaniko-project/executor:debug
    args: [
             "--context=dir://workspace",
             "--destination=gcorradini2023/busybox-latest:0.0.89",
             "--dockerfile=Dockerfile"
    ]
    volumeMounts:
      - name: dockerhub-regcred-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-volume
        mountPath: /workspace
  volumes:
    - name: dockerhub-regcred-secret
      secret:
        secretName: dockerhub-regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-volume
      configMap:
        name: configmap-busybox-latest-040b693780
        items:
          - key: dockerfile
            path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-python-buster-4a16c7408b
  namespace: argocd
spec:
  restartPolicy: Never
  containers:
  - name:  pod-python-buster-4a16c7408b
    image: gcr.io/kaniko-project/executor:debug
    args: [
             "--context=dir://workspace",
             "--destination=gcorradini2023/python-buster:0.0.45",
             "--dockerfile=Dockerfile"
    ]
    volumeMounts:
      - name: dockerhub-regcred-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-volume
        mountPath: /workspace
  volumes:
    - name: dockerhub-regcred-secret
      secret:
        secretName: dockerhub-regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-volume
      configMap:
        name: configmap-python-buster-4a16c7408b
        items:
          - key: dockerfile
            path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-ubuntu-lunar-389375b53e
  namespace: argocd
spec:
  restartPolicy: Never
  containers:
  - name:  pod-ubuntu-lunar-389375b53e
    image: gcr.io/kaniko-project/executor:debug
    args: [
             "--context=dir://workspace",
             "--destination=gcorradini2023/ubuntu-lunar:0.0.75",
             "--dockerfile=Dockerfile"
    ]
    volumeMounts:
      - name: dockerhub-regcred-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-volume
        mountPath: /workspace
  volumes:
    - name: dockerhub-regcred-secret
      secret:
        secretName: dockerhub-regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-volume
      configMap:
        name: configmap-ubuntu-lunar-389375b53e
        items:
          - key: dockerfile
            path: Dockerfile
