---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-busybox-latest-040b693780
  namespace: argocd
data:
  dockerfile: |
    FROM busybox:latest
    ENTRYPOINT ["/busybox/sh", "-ec", "sleep 4000"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-python-buster-4a16c7408b
  namespace: argocd
data:
  dockerfile: |
    FROM python:buster
    ENTRYPOINT ["python", "-m", "http.server 8888"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ubuntu-lunar-389375b53e
  namespace: argocd
data:
  dockerfile: |
    FROM ubuntu:lunar
    ENTRYPOINT ["/bin/bash", "-c", "echo Hello Kaniko from Kubernetes"]
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-busybox-latest-040b693780
  namespace: argocd
spec:
  ttlSecondsAfterFinished: 86400
  template:
    containers:
    - name:  job-busybox-latest-040b693780
      image: gcr.io/kaniko-project/executor:debug
      args: [
               "--context=dir://workspace",
             "--destination=gcorradini2023/busybox-latest:0.0.33",
               "--dockerfile=Dockerfile"
      ]
      volumeMounts:
        - name: dockerhub-regcred-secret
          mountPath: /kaniko/.docker
        - name: dockerfile-volume
          mountPath: /workspace
    volumes:
      - name: dockerhub-regcred-secret
        secret:
          secretName: dockerhub-regcred
          items:
            - key: .dockerconfigjson
              path: config.json
      - name: dockerfile-volume
        configMap:
          name: configmap-busybox-latest-040b693780
          items:
            - key: dockerfile
              path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-python-buster-4a16c7408b
  namespace: argocd
spec:
  ttlSecondsAfterFinished: 86400
  template:
    containers:
    - name:  job-python-buster-4a16c7408b
      image: gcr.io/kaniko-project/executor:debug
      args: [
               "--context=dir://workspace",
             "--destination=gcorradini2023/python-buster:0.0.52",
               "--dockerfile=Dockerfile"
      ]
      volumeMounts:
        - name: dockerhub-regcred-secret
          mountPath: /kaniko/.docker
        - name: dockerfile-volume
          mountPath: /workspace
    volumes:
      - name: dockerhub-regcred-secret
        secret:
          secretName: dockerhub-regcred
          items:
            - key: .dockerconfigjson
              path: config.json
      - name: dockerfile-volume
        configMap:
          name: configmap-python-buster-4a16c7408b
          items:
            - key: dockerfile
              path: Dockerfile
---
# Source: manifest-builder/templates/manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-ubuntu-lunar-389375b53e
  namespace: argocd
spec:
  ttlSecondsAfterFinished: 86400
  template:
    containers:
    - name:  job-ubuntu-lunar-389375b53e
      image: gcr.io/kaniko-project/executor:debug
      args: [
               "--context=dir://workspace",
             "--destination=gcorradini2023/ubuntu-lunar:0.0.15",
               "--dockerfile=Dockerfile"
      ]
      volumeMounts:
        - name: dockerhub-regcred-secret
          mountPath: /kaniko/.docker
        - name: dockerfile-volume
          mountPath: /workspace
    volumes:
      - name: dockerhub-regcred-secret
        secret:
          secretName: dockerhub-regcred
          items:
            - key: .dockerconfigjson
              path: config.json
      - name: dockerfile-volume
        configMap:
          name: configmap-ubuntu-lunar-389375b53e
          items:
            - key: dockerfile
              path: Dockerfile
