name: deploy

on:
  push:
    branches:
      - main

jobs:
  build_manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOY_USER_PAT }}
      - uses: azure/setup-helm@v3

      - name: get HEAD sha
        id: commitsha_head
        run: |
          TEMP=$(git rev-parse HEAD)
          echo "############################################"
          echo $TEMP
          echo "############################################"
          echo "GIT_REV_HEAD=$TEMP" >> $GITHUB_OUTPUT
      - name: copy all Dockerfils to helm builder
        id: copydockerfiles
        run: |
          ls -lah
          rm -rf ./manifest-builder/dockerfile_inputs
          cp -r ./images ./manifest-builder/dockerfile_inputs
          TEMP=$(ls ./manifest-builder/dockerfile_inputs)
          echo "############################################"
          echo $TEMP
          echo "############################################"
      - name: find all Dockerfiles && create a helm values file dynamically
        id: valuesfile
        run: |
          cd ./manifest-builder
          DOCKERFILES=$(find dockerfile_inputs/* -name "Dockerfile")
          cd ../
          VALUESFILE=./manifest-builder/values.yaml
          echo "" > $VALUESFILE
          printf "versionLookup:\n" >> $VALUESFILE
          while read DOCKERFILE_PATH; do
            BASE_KEY=$(echo $DOCKERFILE_PATH | sed 's/:/-/g')
            # TODO: this needs to be a semvar thing in the future
            VERSION=$((1 + $RANDOM % 100))
            KEY_AND_VALUE=$(printf "%s: 0.0.%s" $BASE_KEY $VERSION)
            echo "  $KEY_AND_VALUE" >> $VALUESFILE
          done < <(echo "$DOCKERFILES")
          echo "############################################"
          cat $VALUESFILE
          echo "############################################"
          echo "VALUESFILE=$VALUESFILE" >> $GITHUB_OUTPUT
      - name: build helm templates
        id: helmbuild
        run: |
          cd ./manifest-builder
          helm template -s templates/manifests.yaml . -f values.yaml > ../deploy/manifests.yaml
          echo "############################################"
          cat ../deploy/manifests.yaml
          echo "############################################"
      - name: commit ./deploy changes back
        id: commitback
        run: |
          git config --global user.name 'helmdeployuser'
          git config --global user.email 'helmdeployuser@users.noreply.github.com'
          git config --global pull.rebase false
          ##########################
          FIRST_STATUS=$(git status)
          git add deploy/manifests.yaml
          git add -u
          git commit -am "deploy update ${{ steps.commitsha_head.outputs.GIT_REV_HEAD }}"
          SECOND_STATUS=$(git status)
          git fetch
          BRANCHES=$(git branch)
          echo $FIRST_STATUS
          echo $BRANCHES
          echo $SECOND_STATUS
          ##########################
          git checkout deploy --
          git merge main
          git push origin deploy




